### ISSUE TITLE
Unable to explode Array of JSON in connector.

### ISSUE THREAD

**Issue by Gk1241** [scylladb/kafka-connect-scylladb#102]
Message in my Kafka topic looks something like:
```
{
  "dealId": "wwww",
  "data": [
    {
      "userId": "xxxx",
      "brandName": "xxxx",
      "brandId": xx,
      "displayName": "xxxx"
    },
    {
      "userId": "yyyy",
      "brandName": "yyyy",
      "brandId": yy,
      "displayName": "yyyy"
    }
  ]
}
```

My requirement is to create a separate row for each element in array. Assume dealId, userId will be the primary key for the table, in that case the table would have following rows:
```
dealId   userId
wwww     xxxx
wwww     yyyy
```

Is there any transformation already exist for the same, or do we need to introduce that in this?

**Comment by Gk1241** [comment]
@mykaul @avelanarius @Bouncheck  @dkropachev @Lorak-mmk @dbolshak 

Could you guys please help me for the same?

**Comment by mykaul** [comment]
I believe questions are best answered in the forum - https://forum.scylladb.com - not as GH issues.

**Comment by Bouncheck** [comment]
> I believe questions are best answered in the forum - https://forum.scylladb.com - not as GH issues.

I agree, especially if the question is what SMTs to use. Closing as not planned.
