### ISSUE TITLE
Incorrect source code path in Confluent Hub

### ISSUE THREAD

**Issue by forsberg** [scylladb/kafka-connect-scylladb#23]
The source code and documentation links from the Confluent Hub are incorrect, they point to github.com/**scylla**/kafka-connect-scylladb, should be github.com/**scylladb**/kafka-connect-scylladb

Don't know if this is the culprit line, but it's also wrong:

https://github.com/scylladb/kafka-connect-scylladb/blob/aa89618ccbab7aa2d14da67c7b86a305dd1e914d/pom.xml#L10

**Comment by mailmahee** [comment]
Good Catch @forsberg  - updated.
