### ISSUE TITLE
Missing current-offset and lag when describing connector's consumer groups

### ISSUE THREAD

**Issue by avelanarius** [scylladb/kafka-connect-scylladb#68]
A problem reported by a user on Slack. When using `kafka-consumer-group.sh` to describe the consumer group of the Sink Connector, some of its details (`current-offset` and `lag`) are not correctly filled in:

![Untitled](https://user-images.githubusercontent.com/10003183/157260043-95e5c47c-a5bc-480b-b455-54cd0a47d522.png)

**Comment by avelanarius** [comment]
Issue successfully reproduced locally by me. I can confirm (as the user report stated) that the problem is present only when storing offsets on Scylla is disabled.

**Comment by avelanarius** [comment]
> Issue successfully reproduced locally by me. 

Unfortunately, this was a premature celebration. Upon actually inserting some data into the replicated topic, the columns are correctly updated. @Bouncheck has similar problems to reproduce the issue.

**Comment by canelmas** [comment]
any idea/guidance on how to monitor for example the lag with this connector?

**Comment by avelanarius** [comment]
Upon further inspection, using `kafka-consumer-group.sh` is a good way to monitor the lag of the connector. We were unable to reproduce any issues with it and monitoring with `kafka-consumer-group.sh` works in both modes of storing offsets (both on Kafka and on Scylla).
