### ISSUE TITLE
Cannot use kafka connect offset management with topic regex router

### ISSUE THREAD

**Issue by chiragb1994** [scylladb/kafka-connect-scylladb#74]
If I use a regex router and disable scylladb offset storage table, offsets don't get committed to kafka. This happens because the topic name is changed and the offset details returned by `preCommit` is returning offsets with changed topic name.

Possible solution: Give an option to set table name

**Comment by Bouncheck** [comment]
Hi, this should be solved now by #86.
Regex router should work without a problem.
